# Transpile typescript into javascript
FROM node:lts-alpine
WORKDIR /app
COPY . .
RUN npm install
RUN npm run build

# create image for production
FROM node:lts-buster

ENV TZ=Europe/Zurich

RUN cd ~/ && wget --no-check-certificate -c --header "Cookie: oraclelicense=accept-securebackup-cookie" https://download.oracle.com/otn-pub/java/jdk/16.0.1+9/7147401fd7354114ac51ef3e1328291f/jdk-16.0.1_linux-x64_bin.tar.gz
RUN mkdir /usr/lib/jvm
RUN cd /usr/lib/jvm && tar -xvzf ~/jdk-16.0.1_linux-x64_bin.tar.gz
RUN echo "PATH=\"/usr/lib/jvm/jdk-16.0.1/bin\"" > /etc/environment
RUN echo "JAVA_HOME=\"/usr/lib/jvm/jdk-16.0.1\"" >> /etc/environment
RUN update-alternatives --install "/usr/bin/java" "java" "/usr/lib/jvm/jdk-16.0.1/bin/java" 0
RUN update-alternatives --install "/usr/bin/javac" "javac" "/usr/lib/jvm/jdk-16.0.1/bin/javac" 0
RUN update-alternatives --set java /usr/lib/jvm/jdk-16.0.1/bin/java
RUN update-alternatives --set javac /usr/lib/jvm/jdk-16.0.1/bin/javac

WORKDIR /eve
COPY package*.json ./
RUN npm install --production
COPY --from=0 ./app/dist .

CMD npm start