# Transpile typescript into javascript
FROM node:lts-alpine
WORKDIR /app
COPY . .
RUN npm install
RUN npm run build

# create image for production
FROM node:lts-buster

ENV TZ=Europe/Zurich

RUN cd ~/ && wget --no-check-certificate -c https://github.com/adoptium/temurin16-binaries/releases/download/jdk-16.0.2%2B7/OpenJDK16U-jdk_x64_linux_hotspot_16.0.2_7.tar.gz
RUN mkdir /usr/lib/jvm
RUN cd /usr/lib/jvm && tar -xvzf ~/OpenJDK16U-jdk_x64_linux_hotspot_16.0.2_7.tar.gz
RUN echo "PATH=\"/usr/lib/jvm/jdk-16.0.2+7/bin\"" > /etc/environment
RUN echo "JAVA_HOME=\"/usr/lib/jvm/jdk-16.0.2+7\"" >> /etc/environment
RUN update-alternatives --install "/usr/bin/java" "java" "/usr/lib/jvm/jdk-16.0.2+7/bin/java" 0
RUN update-alternatives --install "/usr/bin/javac" "javac" "/usr/lib/jvm/jdk-16.0.2+7/bin/javac" 0
RUN update-alternatives --set java /usr/lib/jvm/jdk-16.0.2+7/bin/java
RUN update-alternatives --set javac /usr/lib/jvm/jdk-16.0.2+7/bin/javac

WORKDIR /eve
COPY package*.json ./
RUN npm install --production
COPY --from=0 ./app/dist .

CMD npm start