name: ci

on:
  push:
    branches:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/giyomoon/eve
          tags: |
            type=raw,value={{branch}}-{{sha}}-java11
            type=raw,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }},value=java11
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          build-args: |
            NODE_VERSION=lts-buster
            JAVA_PACKAGE=openjdk-11-jre